import Sidebar from '@/components/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <div className="w-72 shrink-0 bg-slate-100 border-r border-slate-200 p-6">
          <h1 className="text-2xl font-semibold mb-3 w">ECHATS PLAYGROUND</h1>
          <Sidebar />
        </div>
        <main className="flex justify-center flex-grow p-16">{children}</main>
      </body>
    </html>
  );
}
